var express = require('express');
var router = express.Router();
var authController = require('./Controllers/AuthController');
router.post('/auth/register', authController.register);
router.post('/auth/login', authController.login);
router.post('/auth/validate', authController.validate_token);
// module.exports = router;
var authMiddleware = require('./MIddleware/AuthMiddleware');
router.get('/hello', authMiddleware.Validate);
module.exports = router;
